### ISSUE TITLE
Hey where is coolstore directory ?

### ISSUE THREAD

**Issue by Kiddinglife** [istioinaction/book-source-code#16]
Hey I bought istioinaction pre-release book from manning. can I know where is coolstore directory ? 

> Before we deploy this, however, we want to inject the Istio service proxy so that this service can
participate in the service mesh. From the coolstore directory of the source code, run the
following command using the istioctl command we introduced earlier:

**Comment by rinormaloku** [comment]
Hi Kiddinglife. 

It should be from the root directory of the source code

**Comment by Kiddinglife** [comment]
yea. I think it is better to say from root director instead of coolstore becasue it loks a bit confusing.

**Comment by rinormaloku** [comment]
It's in the pipeline to get updated. You will find some other inconsistencies until MEAP v16 is released. To inform you in advance (if v16 takes too long) some code snippets refer to files in chapter 7 meanwhile those were moved to chapter 8.
