### ISSUE TITLE
Hey where is gateways: - mesh ?

### ISSUE THREAD

**Issue by Kiddinglife** [istioinaction/book-source-code#17]
In chapter 5.2.5, there is a command: kubectl apply -f ch5/catalog-vs-v2-request-mesh.yaml
where is **gateway: -mesh**  created in ch5/catalog-vs-v2-request-mesh.yaml?
Is **mesh** a reserved gateway name by istio ?
Thx.

**Comment by rinormaloku** [comment]
It applies to all the sidecars within the mesh
