### ISSUE TITLE
Examples for telemetry don't work

### ISSUE THREAD

**Issue by pourquoi42** [istioinaction/book-source-code#18]
When trying one of the examples mentioned by the book about telemetry, I get the following error
```bash
$ kubectl apply -f book-source-code/ch4/enable-ingress-gw-access-logs.yaml 
error: unable to recognize "book-source-code/ch4/enable-ingress-gw-access-logs.yaml": no matches for kind "Telemetry" in version "telemetry.istio.io/v1alpha1"
```
What could be the reason?

**Comment by pourquoi42** [comment]
btw, an example how to modify access logging would be really great, because I would expect it is something quite common to do.

**Comment by rinormaloku** [comment]
Hi Pourquoi

What version of Istio do you have?

```
istioctl version
```

The telemetry API is added in version 1.12

**Comment by pourquoi42** [comment]
That would explain it... 1.9.9 :)
