### ISSUE TITLE
ch4: Getting traffic into cluster "eventually consistent" virtual host & routes not found

### ISSUE THREAD

**Issue by vyom-soft** [istioinaction/book-source-code#24]
Hello,
I created the gateway and the virtualservice as described in the book. 
It worked fine for the first time with gateway routing with virtual service.
The below command showed the response as describe in the book.
istioctl proxy-config route deploy/istio-ingressgateway -o json --name http.8080  -n istio-system

After I changed the host to another value. And making sure that is consistent in Gateway & VirtualService.
the above command did not had the entry for virtual host & route. It shows only the output as described in book for "listener is bound to a blackhole"
I am not sure the "eventually consistent" is not happening for after changing the hosts. I made sure that namespace is correct. And recreated the GW.yaml & VS.yaml.  

Could you please sight where could the issue be.

Thank you

**Comment by vyom-soft** [comment]
So, I created the same in another namespace. Then it works. It does not work in same namespace after recreating the same GW & VS. 
Now I see 2 GW & VS. 
the command $ istioctl proxy-config route deploy/istio-ingressgateway -o json --name http.8080  -n istio-system
shows both of them.

**Comment by rinormaloku** [comment]
Glad that you were able to solve this! :+1:
