### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by SJrX** [istioinaction/book-source-code#26]
Hello, 

I was going to suggest maybe that multi-arch images be created for things so that people who are on a new M1 mac (maybe) or using a raspberry pi based cluster can use the images. That might be a lot of work and I've never actually built a multi arch image.

At the very least, you might want to remove the hard coded [GOARCH in the webapp folder](https://github.com/istioinaction/book-source-code/blob/master/services/webapp/Dockerfile#L7) (maybe it's in other places, I'm just on chapter 2), so that it doesn't compile to amd64 for people who are trying to build the docker images on other platforms.

Cheers

**Comment by rinormaloku** [comment]
I'll see to work on this during the next week.

**Comment by rinormaloku** [comment]
Done! Thanks for opening the issue @SJrX
