### ISSUE TITLE
section 2.3 - Contact from within the cluster times out

### ISSUE THREAD

**Issue by dxps** [istioinaction/book-source-code#27]
Hi there!

This is a great book! Thanks for writing it! :pray: 

Context:
- Istio 1.15.1 - the current version at the time of this writing
- K8S server v1.25.2, and with kubectl v1.25.3
- in a KinD v0.16.0 setup

I'd assume something changed in the naming part since for both `catalog` and `webapp` cases I get a timed out result:
```shell
❯ kubectl run -i --rm --restart=Never dummy --image=curlimages/curl --command -- \
              sh -c 'curl -s http://catalog.istioinaction/items/1'
pod "dummy" deleted
error: timed out waiting for the condition
❯ 
```

Everything else works fine:
- the installation of both services is fine
- through port forwarding (`kubectl port-forward deploy/webapp 8080:8080`) I get the UI with the same state and details as in the book, figure 2.6.

And I tested this on two different (Pop!_OS 22.04 LTS) Linux systems.

I couldn't find any reference about it in the existing (open or closed) issues, so I wanted to ask about it.
Meanwhile, I'll try to find the answer myself and get back here to post it, without any feedback in between.

Thanks.

**Comment by dglaubman** [comment]
Agree with above poster: Great book, but I have same issue he reports.

**Comment by dxps** [comment]
@dglaubman I switched to [k3d](https://k3d.io) and had no problems afterwards. Highly recommended!
I am planning to write an article that showcases the full local setup - from scratch - of how to eventually have a WASM Plugin in Istio.

**Comment by rinormaloku** [comment]
This issue can appear if creating the container is slow. But on a subsequent retry, the container image is cached and it will work.

Happy to hear that you are enjoying the book! :))

**Comment by dxps** [comment]
@rinormaloku Thanks, Rinor, for the feedback!
As mentioned in my last comment, switching to k3d most of the struggle disappeared. :blush:
